# Generated by Django 2.2.5 on 2019-09-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='PastLife',
        ),
    ]
